baseURL = "https://qi-zero.herokuapp.com/"
languageCode = "pt-br"
title = "QI Zero | Um blog sobre tecnologia"
theme = "parsa"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/headroom/headroom.js"
  [[params.plugins.js]]
  URL = "plugins/instafeed/instafeed.min.js"
  [[params.plugins.js]]
  URL = "plugins/masonry/masonry.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/smooth-scroll/smooth-scroll.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  

  
# navigation
[menu]
    
  [[menu.main]]
  name = "Sobre"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Contato"
  URL = "contact"
  weight = 3


[params]
logo = "images/logo.png"
home = "Início"
# hompage layout ( two layout is available,  you can set the another layout by change the value of homeLayoutToggle "true" to "false")
homeLayoutToggle = true
# Meta data
description = "This is meta description"
# about author
author = "Luiz Gabriel"
authorImage = "images/banner-img.png"
shortDescription = "Bacharel em Engenharia de Computação - IFCE"
# Contact Form Action
contactFormAction = "#"
# Google Analitycs
googleAnalitycsID = "Your ID"
# copyright
copyright = "QI Zero | Todos os direitos reservados."

  # Preloader
  [params.preloader]
  enable = true
  
  # search
  [params.search]
  enable = true

  # Instagram feed
  [params.instafeed]
  enable = false
  userID = "4044026246"
  accessToken = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"

  # footer
  [params.footer]

    #address
    [[params.footer.addresses]]
    address = "Fortaleza - CE"
    
    #[[params.footer.addresses]]
    #address = "6 rip carl Avenue CA 90733"
    
    #contact information
    [[params.footer.contacts]]
    contactInfo = "Tel: +55 85 99961-2848"
    
    [[params.footer.contacts]]
    contactInfo = "Email: luizgabriel.info@gmail.com"


  # social site
  [[params.social]]
  icon = "ti-facebook"
  URL = "https://facebook.com/luiz.gabriel.cristo"
  
  #[[params.social]]
  #icon = "ti-twitter-alt"
  #URL = "#"
  
  [[params.social]]
  icon = "ti-linkedin"
  URL = "https://www.linkedin.com/in/luiz-gabriel-lacerda"
  
  [[params.social]]
  icon = "ti-github"
  URL = "https://github.com/luizgabriel"
